# @file mods.toml
# @spec TOML v0.5.0 (https://github.com/toml-lang/toml)
modLoader="javafml" # forge FML java
loaderVersion="[41,)"
issueTrackerURL="https://github.com/stfwi/anthillinside/issues/"
license="MIT"

[[mods]]
modId="anthillinside"
version="${file.jarVersion}"
displayName="Anthill Inside"
description="Adds 'natural' automation with Redstone Ants. Pratchett Readers know the term."
authors="wilechaote"
credits=""
updateJSONURL="https://raw.githubusercontent.com/stfwi/anthillinside/versions/1.19.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/anthill-inside"
logoFile="logo.png"

[[dependencies.anthillinside]]
  modId="forge"
  mandatory=true
  versionRange="[41,)"
  ordering="NONE"
  side="BOTH"

[[dependencies.anthillinside]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.19,1.20)"
  ordering="NONE"
  side="BOTH"
